//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDemo.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPUCService")]
    public interface IPUCService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPUCService/SendRequest", ReplyAction="http://tempuri.org/IPUCService/SendRequestResponse")]
        string SendRequest(string sendDataXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPUCService/SendRequest", ReplyAction="http://tempuri.org/IPUCService/SendRequestResponse")]
        System.Threading.Tasks.Task<string> SendRequestAsync(string sendDataXML);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPUCServiceChannel : ClientDemo.ServiceReference1.IPUCService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PUCServiceClient : System.ServiceModel.ClientBase<ClientDemo.ServiceReference1.IPUCService>, ClientDemo.ServiceReference1.IPUCService {
        
        public PUCServiceClient() {
        }
        
        public PUCServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PUCServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PUCServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PUCServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendRequest(string sendDataXML) {
            return base.Channel.SendRequest(sendDataXML);
        }
        
        public System.Threading.Tasks.Task<string> SendRequestAsync(string sendDataXML) {
            return base.Channel.SendRequestAsync(sendDataXML);
        }
    }
}
